blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/orgs/amplience-ops/discussions
    about: For questions or discussions, please use GitHub Discussions instead of creating an issue.
